### PR TITLE
Upgrade to 0.7

### PR DESCRIPTION
**Pull request by Vaibhavdixit02**

### CODE REVIEW

**Comment by xukai92** [comment]
When will 0.7 be officially released?

**Comment by ChrisRackauckas** [comment]
At least by JuliaCon.

**Comment by xukai92** [comment]
Sounds great. I remember it was said in last year's JuliaCon 0.7 will be 1.0 - is this still ture? 

BTW I didn't manage to get a ticket for this year's JuliaCon (was sold out when I was trying to buy). Dunno whether there will be more released but I sign up the waiting list.

**Comment by ChrisRackauckas** [comment]
Yes, v0.7 is v1.0 but with deprecation warnings to help you upgrade.

**Pull request merged**
