### PR TITLE
Some changes to Sobol

### PR DESCRIPTION
**Pull request by Vaibhavdixit02**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
add a test for what got fixed.

**Comment by Vaibhavdixit02** [comment]
There isn't really any change in the output, it is just a bit of re-writing the trajectory as the standard way instead of the arbitrary way I was doing earlier. I think we can just merge this for now

**Comment by ChrisRackauckas** [comment]
Looks like it has a test failure

**Comment by Vaibhavdixit02** [comment]
This also has performance regression, I am going to close this.

**Pull request closed without merging**
